sudo: required
language: c

os:
    - linux

compiler:
    - gcc-5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

before_install:
  - if [ ! -f .depend ]; then touch .depend; fi; sudo rm /usr/bin/gcc; sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
 
script:
- make depend
- make
